#ARG VARIANT="3.12"
FROM mcr.microsoft.com/vscode/devcontainers/ruby:2.7
## install system package
#RUN apk add --no-cache -U ruby ruby-dev make gcc musl-dev zlib-dev
## install ruby package
RUN gem install solargraph rubocop
